version: '3.7'

services:
  app:
    image: hub.docker.local:5000/mobility-suite/common.docker.elastic.co.elasticsearch.elasticsearch:7.16.2
    env_file: .env
    ports:
      - 9920:9200
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms${HEAP_SIZE:-4G} -Xmx${HEAP_SIZE:-4G}"
    volumes:
      - data${VV}:/usr/share/elasticsearch/data
    networks:
      - es-net
      - traefik-net
    deploy:
      replicas: 1
      placement:
        constraints: [ node.labels.resource_server == true ]
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.es_http.loadbalancer.server.port=9200"

        - "traefik.http.routers.es_http-internal.entrypoints=elasticsearch"
        - "traefik.http.routers.es_http-internal.rule=PathPrefix(`/`)"
        - "traefik.http.routers.es_http-internal.service=es_http"

secrets:
  connect_info.yaml:
    file: connect_info.yaml

volumes:
  data${VV}:
networks:
  es-net:
    external: true
  traefik-net:
    external: true
